FROM almalinux:9

WORKDIR /opt
RUN dnf install -y git clang make openssl-devel cmake clang-tools-extra
RUN dnf install -y epel-release
RUN dnf install -y cppcheck
RUN git clone --depth 1 --branch v1.3.11 https://github.com/eclipse/paho.mqtt.c.git
WORKDIR /opt/paho.mqtt.c
RUN cmake -DPAHO_BUILD_STATIC=TRUE -DPAHO_BUILD_SHARED=FALSE -DPAHO_WITH_SSL=TRUE
RUN make
RUN make install
ENV CC clang
RUN eval $CC -v
