FROM debian:11

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
      clang-13 \
      clang-tools-13 make \
      libpaho-mqtt-dev libpaho-mqtt1.3 \
      libbsd-dev cppcheck clang-format
