FROM debian:10

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
      git \
      clang-13 \
      clang-tools-13 make cmake \
      cppcheck clang-format
RUN apt-get install -y --no-install-recommends \
      ca-certificates libssl-dev
ENV CC clang-13
RUN eval $CC -v
WORKDIR /opt
RUN git clone --depth 1 --branch v1.3.11 https://github.com/eclipse/paho.mqtt.c.git
WORKDIR /opt/paho.mqtt.c
RUN cmake -DPAHO_BUILD_STATIC=TRUE -DPAHO_BUILD_SHARED=FALSE -DPAHO_WITH_SSL=TRUE
RUN make
RUN make install

WORKDIR /opt
