FROM debian:11

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
      gcc \
      clang-13 \
      clang-tools-13 make \
      libpaho-mqtt-dev libpaho-mqtt1.3 \
      cppcheck clang-format
WORKDIR /opt
ENV CC clang-13
RUN eval $CC -v
