FROM debian:10

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
      git \
      clang-13 \
      clang-tools-13 make cmake \
      cppcheck clang-format
RUN apt-get install -y --no-install-recommends \
      ca-certificates

ENV CC clang-13
RUN eval $CC -v

WORKDIR /opt
RUN git clone --depth 1 --branch v1.3.11 https://github.com/eclipse/paho.mqtt.c.git
WORKDIR /opt/paho.mqtt.c
RUN cmake -DPAHO_BUILD_STATIC=TRUE -DPAHO_BUILD_SHARED=FALSE -DPAHO_WITH_SSL=FALSE
RUN make
RUN make install

# symbolic link for Makefile to have the same path for Debian10 and RHEL8
RUN mkdir -p /usr/local/lib64/
RUN ln -s /usr/local/lib/libpaho-mqtt3a.a /usr/local/lib64/libpaho-mqtt3a.a

WORKDIR /opt
