enum error_codes {
  OK,
  ERROR_USAGE,
  ERR_INVALID_STATE,
  ERROR_MQTT_CONNECT,
  ERROR_OPEN_SERIAL_PORT,
  ERROR_SETUP_SERIAL_PORT,
  ERROR_CONFIG_FILE,
  ERROR_BAUD_NOT_SUPPORTED,
  ERROR_TCSETATTR_FAILED,
  ERROR_TCFLUSH_FAILED
};
