name: Coverity Scan
permissions:
  contents: read
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # Daily at 5:00 UTC

jobs:
  scan-latest:
    runs-on: ubuntu-latest
    container:
      image: debian:11
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Dependencies
        run: |
          set -x
          set -e
          apt-get update
          apt-get -y upgrade
          apt-get -y install \
            git \
            curl \
            cppcheck \
            wget \
            build-essential \
            autoconf-archive \
            clang-tools-13 \
            clang-13 clang-format \
            make \
            libpaho-mqtt-dev \
            libpaho-mqtt1.3
      - name: Download Coverity Build Tool
        run: |
          wget -q https://scan.coverity.com/download/linux64 --post-data "token=$TOKEN&project=rapidbus%2Frapidbus" -O coverity_tool.tgz
          mkdir coverity_tool
          tar xzf coverity_tool.tgz --strip 1 -C coverity_tool
          rm coverity_tool.tgz
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}

      - name: Debug
        run: |
          pwd
          ls -al
          ls -al coverity_tool

      - name: Build
        run: |
          export PATH=`pwd`/coverity_tool/bin:$PATH
          echo $PATH
          cd src
          cov-configure --template --compiler clang-13 --comptype clangcc
          cov-build --dir cov-int make -j 1
          cat cov-int/build-log.txt

      - name: Submit the result to Coverity Scan
        run: |
          cd src
          tar -czvf rapidbus.tar.gz cov-int
          curl \
            --form token=$TOKEN \
            --form email=maco@blava.net \
            --form file=@rapidbus.tar.gz \
            --form version=main \
            --form description="`git rev-parse HEAD`" \
            https://scan.coverity.com/builds?project=rapidbus%2Frapidbus
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
